config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources:todos do
    member do
      post :check
    end
  end

  root "todos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates_presence_of :title, :due_date, :description
  # 用 validates_presence_of 這個指令讓表單中的所有區塊都成為必填項目。當使用者送出沒有滿足必填項目的表單時，在存進資料庫前就會被擋下來。
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, :only => [:show, :edit, :update, :destroy, :check]
  # 透過 before_action 來篩選指定動作，我們稱之為 過濾器 (Filter)。除了 before_action 之外，Rails 也提供 around_action 和 after_action 來讓我們來定義進入 action 之中或之後來執行特定的方法。其中 before_action 最為常用。
  # 
  # before_action 也可以是回呼方法 (Callback Method) 的一種。除了針對 Controller 之外，也有針對 Model (也就是 Active Record) 的 Callback Method. 我們會在後來的章節，跟大家介紹。關於 Active Record 的 Callback Method，你可以參考官方指南。
  def index
    @todos = Todo.all
    
  end

  def new
    @todo = Todo.new
    
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      redirect_to todos_url
    else
      render :action => :new
    end
  end

  # def show
  #   @todo=Todo.find(params[:id])
    
  # end

  # def edit
  #   @todo=Todo.find(params[:id])
    
  # end

  def update
    # @todo=Todo.find(params[:id])
    if @todo.update_attributes(todo_params)

      redirect_to todo_url(@todo)
    else
      render :action => :edit
    end
  end

  def destroy
    # @todo=Todo.find(params[:id])
    @todo.destroy

    redirect_to todos_url
    
  end

  def check
    # @todo=Todo.find(params[:id])
    @todo.update(checkbox: !(@todo.checkbox))
    
  end
private
  def set_todo
    @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:title,:due_date,:description)
  
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<div class="form container">
  <% if @todo.errors.present? %>
  <ul>
    <% @todo.errors.each do |error, message| %>
      <li> <%= "#{error.capitalize}  #{message}" %></li>
    <% end %>
  </ul>
<% end %>

<!-- 首先是 Ruby 的部分，程式碼的最外層用if...end 包圍住 HTML 元素，意思是，如果 if 的條件式成立，才去把 HTML 內容顯示出來。而 if 的條件寫成 @todo.errors.present?，意思是「@todo 帶有錯誤訊息」——當@todo跑到 Todo model 時，若驗證不通過，validates_presence_of會把錯誤資訊塞回@todo，存進.errors方法。所以如果.errors裡面有存東西，就表示驗證不通過。 -->
<!-- 接下來就把.errors的資料一筆筆讀出來，在 Ruby 裡，「一筆筆讀資料」會用 .each方法來做。把讀出來的資料塞進 <li></li>裡，就會跑出一個個清單項目。 -->
  <%= form_for @todo do |f| %>
    <div class="form-group">    
      <%= f.label :title, "Title" %>
      <%= f.text_field :title,class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :due_date, "Due Date" %>
      <%= f.text_field :due_date,class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :description, "Description" %>
      <%= f.text_area :description,class:"form-control" %>
    </div>
    <%= f.submit %>
  <% end %>
</div>

app/views/todos/edit.html.erb
<%= render :partial => "form" %>

app/views/todos/index.html.erb
<div class="container">
  <table class="table table-striped table-condensed table-hover">
    <h1>To-Do List</h1>
    <tr>
      <td>Status</td>
      <td>Item</td>
      <td>Due Date</td>
      <td>Details</td>
      <td>Delete</td>
    </tr>
    <% @todos.each do |todo| %>
      <tr>
        <% if todo.due_date  < Date.today%>
          <td> <%= check_box_tag('todo.title','todo.title',todo.checkbox,disabled: true) %></td>
          <td> <%= label_tag(todo.checkbox,todo.title) %> </td>
          <td> <%= todo.due_date %> </td>
          <td> <%= link_to 'Show',todo_path(todo) %> </td>
          <td>Expired</td>
        <% else %>
          <td> <%= check_box_tag :checkbox , true , todo.checkbox , data: { url: check_todo_path(todo),method: :post, remote: true} %></td>
          <td> <%= label_tag(todo.checkbox,todo.title) %> </td>
          <td> <%= todo.due_date %> </td>
          <td> <%= link_to 'Show',todo_path(todo) %> </td>
          <td> 
            <%= link_to todo_path(todo), method: :delete, data:{ confirm: "Are you sure?"} do %> 
              <span class="glyphicon glyphicon-remove"></span>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>

  <%= link_to 'New Item', new_todo_path %>
</div>

app/views/todos/new.html.erb
<%= render :partial => "form" %>

<!-- 你使用了render指令，意即接下來 Rails 會去找 .html.erb 的檔案，他會優先在 views 的當前路徑下尋找對應的 template -->
<!-- 再來，你指定的參數是 partial，所以 Rails 知道要去找用底線開頭的名稱 -->
<!-- 最後，你指定了 form 這個名稱，所以 Rails 就會去 render _form.html.erb 這個檔案裡面的內容。 -->

app/views/todos/show.html.erb
<%= @todo.title %><br/>
<%= @todo.due_date %>
<%= simple_format(@todo.description) %>

<p><%= link_to 'Edit',edit_todo_path %></p>

<p><%= link_to 'Back to index',todos_path %></p>